<a href="https://colab.research.google.com/github/katetarasenko/Kurs_4_Practical1_Tarasenko/blob/main/Practical_1_Tarasenko.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Завдання 1

Створити одновимірний масив зі значенням и квадратних коренів з кожного натурального числа, починаючи з 1, і вивести ці значеня

In [1]:
import numpy as np

In [2]:
n = 10  # кількість чисел,

# Створюємо масив натуральних чисел від 1 до n
natural_numbers = np.arange(1, n + 1)

# Обчислюємо квадратні корені
square_roots = np.sqrt(natural_numbers)

# Виводимо результат
print("Натуральні числа:", natural_numbers)
print("Квадратні корені:", square_roots)

Натуральні числа: [ 1  2  3  4  5  6  7  8  9 10]
Квадратні корені: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


Завдання 2

Створити двовимірний масив розміром 3*3, заповнити його значеннями коренів 4 ступеня перших дійсних чисел

In [3]:
real_numbers = np.arange(1, 10).reshape(3, 3)

# Обчислюємо четверті корені
fourth_roots = np.power(real_numbers, 1/4)

# Виводимо результат
print("Масив дійсних чисел:\n", real_numbers)
print("Масив четвертих коренів:\n", fourth_roots)

Масив дійсних чисел:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Масив четвертих коренів:
 [[1.         1.18920712 1.31607401]
 [1.41421356 1.49534878 1.56508458]
 [1.62657656 1.68179283 1.73205081]]


завдання 3

Створити масив розміром 3*3, заповнити випадковими натуральними числами від 1 до 50, знайти суму елементів кожного рядка

In [4]:
#створити масив і заповнення його рандомними числами
random_array = np.random.randint(1, 51, size=(3, 3))

# Обчислюємо суму елементів кожного рядка
row_sums = np.sum(random_array, axis=1)

# Виводимо результат
print("Випадковий масив:\n", random_array)
print("Сума елементів кожного рядка:\n", row_sums)

Випадковий масив:
 [[50 35 17]
 [26 19 19]
 [38 44  1]]
Сума елементів кожного рядка:
 [102  64  83]


Завдання 4

Створити масив розміром 4*4, заповнити його випадковими числами від -0.9 до 0.9 і вивести його

In [5]:
random_array = np.random.uniform(-0.9, 0.9, size=(4, 4))

# Виводимо результат
print("Масив випадкових чисел від -0.9 до 0.9:\n", random_array)

Масив випадкових чисел від -0.9 до 0.9:
 [[ 0.23159179  0.65657227 -0.00859021  0.8350354 ]
 [-0.03775994  0.48554548 -0.66781434  0.61256531]
 [ 0.45976932  0.52637068 -0.63124335  0.09503675]
 [ 0.11504088  0.13519123  0.08625846  0.04416899]]


Завдання 5

Створити 2 одновимірних масиви розмірами по 7, заповнити їх випадковими цілими числами в діапазоні від 1 до 5, виконати на них поелементні операції додавання, віднімання, множення

In [6]:
array1 = np.random.randint(1, 6, size=7)
array2 = np.random.randint(1, 6, size=7)

# Поелементне додавання
addition = np.add(array1, array2)

# Поелементне віднімання
subtraction = np.subtract(array1, array2)

# Поелементне множення
multiplication = np.multiply(array1, array2)

# Виводимо результати
print("Перший масив:\n", array1)
print("Другий масив:\n", array2)
print("Поелементне додавання:\n", addition)
print("Поелементне віднімання:\n", subtraction)
print("Поелементне множення:\n", multiplication)

Перший масив:
 [4 2 3 3 4 4 2]
Другий масив:
 [5 5 1 2 1 1 2]
Поелементне додавання:
 [9 7 4 5 5 5 4]
Поелементне віднімання:
 [-1 -3  2  1  3  3  0]
Поелементне множення:
 [20 10  3  6  4  4  4]


Завдання 6

створити дві матриці 3*3 та заповнити їх довільними цілими числами від 0 до 5 та знайти їх добуток

In [7]:
matrix1 = np.random.randint(0, 6, size=(3, 3))
matrix2 = np.random.randint(0, 6, size=(3, 3))

# Знаходимо їх добуток
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця:
 [[4 5 4]
 [4 0 1]
 [3 5 1]]
Друга матриця:
 [[0 2 2]
 [4 1 5]
 [4 1 5]]
Добуток матриць:
 [[36 17 53]
 [ 4  9 13]
 [24 12 36]]


Завдання 7

створити 2 матриці розмірами 2*3 та 3*4, заповнити випадковими числами від 1 до 7 та перемножити їх між собою

In [8]:
matrix1 = np.random.randint(1, 8, size=(2, 3))
matrix2 = np.random.randint(1, 8, size=(3, 4))

# Перемножуємо матриці
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця (2x3):\n", matrix1)
print("Друга матриця (3x4):\n", matrix2)
print("Добуток матриць (2x4):\n", product)

Перша матриця (2x3):
 [[1 3 5]
 [1 2 6]]
Друга матриця (3x4):
 [[4 5 5 3]
 [6 3 3 1]
 [5 1 2 6]]
Добуток матриць (2x4):
 [[47 19 24 36]
 [46 17 23 41]]


Завдання 8

Створити матрицю розміром 2*2, заповнити її випадковими числами від 1 до 15 та знайти обернену матрицю

In [9]:
matrix = np.random.randint(1, 16, size=(2, 2))

# Знаходимо обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

# Виводимо результати
print("Початкова матриця:\n", matrix)
print("Обернена матриця:\n", inverse_matrix)

Початкова матриця:
 [[ 1  6]
 [14 10]]
Обернена матриця:
 [[-0.13513514  0.08108108]
 [ 0.18918919 -0.01351351]]


Завдання 9

Створити матрицю розміром 3*3 заповнити її випадковими цілими числами в діапазоні від 3 до 15 та транспонувати її

In [10]:
matrix = np.random.randint(3, 16, size=(3, 3))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо результати
print("Початкова матриця:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)

Початкова матриця:
 [[ 9  3  4]
 [ 4 11  4]
 [ 5 13  5]]
Транспонована матриця:
 [[ 9  4  5]
 [ 3 11 13]
 [ 4  4  5]]


Завдання 10

Створити матрицю розміром 3*4 та вектор розміром 4*1, заповнити і матрицю і вектор випадковими цілими числами від 1 до 10, знайти добуток матриці на вектор

In [11]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результати
print("Початкова матриця (3x4):\n", matrix)
print("Вектор (4x1):\n", vector)
print("Добуток матриці на вектор (3x1):\n", product)

Початкова матриця (3x4):
 [[ 8  3  7 10]
 [ 3  8  1 10]
 [ 2  3  5  7]]
Вектор (4x1):
 [[1]
 [2]
 [9]
 [8]]
Добуток матриці на вектор (3x1):
 [[157]
 [108]
 [109]]


Завдання 11

Створити матрицю розміром 2*3, та вектор розміром 3*1, заповнити матрицю і вектор випадковими дійсними числами від 0 до 1, знайти добуток матриці на вектор

In [12]:
matrix = np.random.uniform(0, 1, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3, 1))

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результати
print("Початкова матриця (2x3):\n", matrix)
print("Вектор (3x1):\n", vector)
print("Добуток матриці на вектор (2x1):\n", product)

Початкова матриця (2x3):
 [[0.51302624 0.8775214  0.1523343 ]
 [0.12999473 0.30511342 0.78138582]]
Вектор (3x1):
 [[0.22151558]
 [0.84784139]
 [0.09998545]]
Добуток матриці на вектор (2x1):
 [[0.87287349]
 [0.36561086]]


Завдання 12

Створити дві матриці розміром 3*3, заповнити їх випадковими цілими числами в діапазоні від 1 до 5 та знайти добуток всіх елементів першої матриці.

In [13]:
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

#добуток всіх елементів першої матриці
product_of_elements = np.prod(matrix1)

# Виводимо результати
print("Перша матриця (3x3):\n", matrix1)
print("Друга матриця (3x3):\n", matrix2)
print("Добуток всіх елементів першої матриці:\n", product_of_elements)

Перша матриця (3x3):
 [[4 5 1]
 [4 3 5]
 [3 2 2]]
Друга матриця (3x3):
 [[5 3 4]
 [5 3 3]
 [4 5 1]]
Добуток всіх елементів першої матриці:
 14400


Завдання 13

Створити 2 матриці розміром 3*3 та заповнити їх випадковими дійсними числами від -1 до 1 та знайти різницю їх елементів

In [14]:
matrix1 = np.random.uniform(-1, 1, size=(3, 3))
matrix2 = np.random.uniform(-1, 1, size=(3, 3))

# Знаходимо різницю між відповідними елементами матриць
difference = matrix1 - matrix2

# Виводимо результати
print("Перша матриця (3x3):\n", matrix1)
print("Друга матриця (3x3):\n", matrix2)
print("Різниця між матрицями (3x3):\n", difference)

Перша матриця (3x3):
 [[ 0.83366713  0.31072407  0.76834211]
 [-0.17402297  0.32664683  0.33744114]
 [ 0.41149578 -0.09686297 -0.82725946]]
Друга матриця (3x3):
 [[-0.92442191  0.40405511  0.30831754]
 [-0.64139853  0.16940784 -0.95091505]
 [-0.69633213 -0.06651382  0.90329419]]
Різниця між матрицями (3x3):
 [[ 1.75808903 -0.09333103  0.46002457]
 [ 0.46737556  0.15723899  1.28835619]
 [ 1.10782791 -0.03034915 -1.73055365]]


Завдання 14

Створити матрицю розміром 3*3, заповнити її випадковими дійсними числами від -3 до 3 та знайти суму елементів на головній діагоналі

In [15]:
matrix = np.random.uniform(-3, 3, size=(3, 3))
diagonal_elements = np.diagonal(matrix)

# Знаходимо суму елементів на головній діагоналі
sum_diagonal = np.sum(diagonal_elements)

# Виводимо результати
print("Матриця (3x3):\n", matrix)
print("Елементи на головній діагоналі:\n", diagonal_elements)
print("Сума елементів на головній діагоналі:\n", sum_diagonal)

Матриця (3x3):
 [[-1.40631498  2.08198428 -0.95045828]
 [-1.26096888  2.31044039 -2.05129813]
 [-2.81949401  1.05817865  0.97935129]]
Елементи на головній діагоналі:
 [-1.40631498  2.31044039  0.97935129]
Сума елементів на головній діагоналі:
 1.8834766905508897


Завдання 15

Створити матрицю розміром 3*3 , заповнити її випадковими дійсними числами в діапазоні від -2 до 2 та знайти вектор-стовпчик, що містить середнє арифметичне значення елементів кожного стовпчика матриці

In [16]:
matrix = np.random.uniform(-2, 2, size=(3, 3))

# середнє арифметичне значення елементів кожного стовпчика
mean_per_column = np.mean(matrix, axis=0)

# Перетворюємо результат у вектор-стовпчик
mean_vector = mean_per_column.reshape(-1, 1)

# Виводимо результати
print("Матриця (3x3):\n", matrix)
print("Вектор-стовпчик середніх значень кожного стовпчика:\n", mean_vector)

Матриця (3x3):
 [[-1.16392628  1.84062112  0.47414923]
 [ 0.81717399  0.2094148   0.95991327]
 [ 0.47471807 -0.97432549  1.4300468 ]]
Вектор-стовпчик середніх значень кожного стовпчика:
 [[0.04265526]
 [0.35857014]
 [0.9547031 ]]
